apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-alpine-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: helm-charts/nginx-deployment
    repoURL: https://github.com/praveenghuge/github-actions-test
    targetRevision: HEAD
  syncPolicy: {}
